# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "(^.idea/)"
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-yaml
          - id: check-added-large-files
            args: ["--maxkb=784"]
          - id: check-merge-conflict
          - id: detect-private-key
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: detect-private-key
          - id: mixed-line-ending
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: ["-d relaxed"]

    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.18.2
      hooks:
        - id: gitleaks
          args: ["--baseline-path", ".gitleaks.baseline.json"]

    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.1-beta
      hooks:
        - id: hadolint-docker

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.6
      hooks:
      -   id: shellcheck
