version: '3'
volumes:
  postgres-data:
  pgadmin-data:
services:
  postgres:
    build:
      context: ./docker-compose/postgres
    shm_size: '128mb'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRESQL_MULTIPLE_DATABASES=jooq_demo
    ports:
      - '5432:5432'
    volumes:
      - "./docker-compose/postgres/initdb.d:/docker-entrypoint-initdb.d:Z"
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'
