version: '3'
volumes:
  postgres-data:
  pgadmin-data:
services:
  postgres:
    build:
      context: ./docker-compose/postgres
    shm_size: '128mb'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRESQL_MULTIPLE_DATABASES=jooq_demo
    ports:
      - '5432:5432'
    volumes:
      - "./docker-compose/postgres/initdb.d:/docker-entrypoint-initdb.d:Z"
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'

  kroki:
    profiles:
      - doc
    image: yuzutech/kroki:0.24.1
    ports:
      - "8000:8000"
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_SAFE_MODE=UNSAFE
  mermaid:
    profiles:
      - doc
    image: yuzutech/kroki-mermaid:0.24.1
    expose:
      - "8002"
